// Tests for the in-tree SHA-256, HMAC-SHA256, constant-time compare, cleanse and OS randomness.
// One executable, one group per invocation: crypto_test <group>. Every digest check runs through
// both Backend::Auto (the SHA extensions when this CPU has them) and Backend::Portable (reference).
// Expected digests come from independent sources: the FIPS 180-4 / RFC 4231 published vectors and
// tests/crypto_vectors.h, generated by tests/support/generate_crypto_vectors.py with Python hashlib.
#include "crypto/crypto.h"
#include "crypto_vectors.h"

#include <algorithm>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <iostream>
#include <set>
#include <stdexcept>
#include <string>
#include <thread>
#include <vector>


namespace {
using namespace sp::crypto;

#define CHECK(cond)                                                                                   \
  do {                                                                                                \
    if (!(cond)) {                                                                                    \
      std::fprintf(stderr, "%s:%d: check failed: %s\n", __FILE__, __LINE__, #cond);                   \
      std::exit(1);                                                                                   \
    }                                                                                                 \
  } while (false)

constexpr Backend kBackends[] = {Backend::Auto, Backend::Portable};
const char* name(Backend b) { return b == Backend::Auto ? (sha256_accelerated() ? "auto/sha-ni" : "auto/portable") : "portable"; }

std::string hex(const Sha256Digest& digest) {
  static constexpr char digits[] = "0123456789abcdef";
  std::string out;
  for (auto c : digest) { out += digits[c >> 4]; out += digits[c & 15]; }
  return out;
}
std::string hex_prefix(const Sha256Digest& digest, std::size_t n) { return hex(digest).substr(0, 2 * n); }

std::string message(std::size_t n) {
  std::string m(n, '\0');
  for (std::size_t i = 0; i < n; ++i) m[i] = static_cast<char>((i * 167 + 13) & 0xFF);
  return m;
}
std::string key(std::size_t n) {
  std::string k(n, '\0');
  for (std::size_t i = 0; i < n; ++i) k[i] = static_cast<char>((i * 29 + 5) & 0xFF);
  return k;
}

struct Rng {
  std::uint64_t s;
  std::uint64_t next() { s ^= s << 13; s ^= s >> 7; s ^= s << 17; return s; }
  std::size_t below(std::size_t n) { return static_cast<std::size_t>(next() % n); }
};

void sha256_vectors() {
  struct Vector { std::string message; const char* digest; };
  const std::vector<Vector> published = {
      // FIPS 180-4 / NIST examples.
      {"", "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"},
      {"abc", "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"},
      {"abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq",  // 448 bits
       "248d6a61d20638b8e5c026930c3e6039a33ce45964ff2167f6ecedd419db06c1"},
      {"abcdefghbcdefghicdefghijdefghijkefghijklfghijklmghijklmnhijklmnoijklmnopjklmnopqklmnopqrlmnopqrsmnopqrstnopqrstu",  // 896 bits
       "cf5b16a778af8380036ce59e7b0492370b249b11e8f07a51afac45037afee9d1"},
      {std::string(1000000, 'a'), "cdc76e5c9914fb9281a1c7e284d73e67f1809a48a497200e046d39ccc7112cd0"},
  };
  for (auto backend : kBackends) {
    for (const auto& v : published) CHECK(hex(sha256(v.message, backend)) == v.digest);
    // Every length 0..300 against hashlib; this includes the padding boundaries 55/56/57, 63/64/65,
    // 119/120/121 and 127/128/129 where the length field spills into an extra block.
    for (std::size_t n = 0; n <= 300; ++n) {
      const auto m = message(n);
      if (hex(sha256(m, backend)) != sp::crypto_vectors::kLengthDigests[n]) {
        std::fprintf(stderr, "length %zu mismatch on %s\n", n, name(backend));
        std::exit(1);
      }
    }
    // The pointer/size overload and the string_view overload agree.
    const auto m = message(129);
    CHECK(sha256(m.data(), m.size(), backend) == sha256(std::string_view(m), backend));
  }
  std::printf("sha256_vectors ok; Auto backend = %s\n", name(Backend::Auto));
}

void sha256_streaming() {
  Rng rng{0x9e3779b97f4a7c15ULL};
  for (auto backend : kBackends) {
    // Byte-at-a-time for every length 0..300.
    for (std::size_t n = 0; n <= 300; ++n) {
      const auto m = message(n);
      Sha256 h(backend);
      for (char c : m) h.update(&c, 1);
      CHECK(hex(h.finish()) == sp::crypto_vectors::kLengthDigests[n]);
    }
    // Random chunkings of random lengths equal the one-shot digest (and hashlib for n <= 300).
    for (int round = 0; round < 3000; ++round) {
      const std::size_t n = round % 5 == 0 ? rng.below(70000) : rng.below(600);
      const auto m = message(n);
      Sha256 h(backend);
      for (std::size_t pos = 0; pos < n;) {
        const std::size_t cap = n - pos;
        std::size_t take = rng.below(4) == 0 ? rng.below(200) : rng.below(70);
        take = std::min(take, cap);
        if (take == 0 && rng.below(3) != 0) take = 1;
        h.update(m.data() + pos, take);
        pos += take;
      }
      const auto streamed = h.finish();
      CHECK(streamed == sha256(m, backend));
      CHECK(streamed == sha256(m, Backend::Portable));
      if (n <= 300) CHECK(hex(streamed) == sp::crypto_vectors::kLengthDigests[n]);
    }
    // Finish idempotence and misuse.
    {
      Sha256 h(backend);
      CHECK(!h.finished());
      h.update("abc", 3);
      const auto first = h.finish();
      CHECK(h.finished());
      CHECK(hex(first) == "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad");
      CHECK(h.finish() == first);
      CHECK(h.finish() == first);
      bool threw = false;
      try { h.update("x", 1); } catch (const std::logic_error&) { threw = true; }
      CHECK(threw);  // a finished hash is never silently extended
      CHECK(h.finish() == first);  // and the refused update changed nothing
      threw = false;
      try { h.update(nullptr, 0); } catch (const std::logic_error&) { threw = true; }
      CHECK(threw);  // even an empty update after finish is refused: the contract does not depend on the size
      h.reset();
      CHECK(!h.finished());
      h.update("abc", 3);
      CHECK(h.finish() == first);
      h.reset();
      CHECK(hex(h.finish()) == sp::crypto_vectors::kLengthDigests[0]);  // reset + finish = empty message
      // A copy taken mid-stream is an independent continuation.
      Sha256 base(backend);
      base.update(message(100));
      Sha256 branch = base;
      base.update(message(50));
      branch.update(std::string(50, 'z'));
      CHECK(base.finish() == sha256(message(100) + message(50), backend));
      CHECK(branch.finish() == sha256(message(100) + std::string(50, 'z'), backend));
    }
  }
  std::printf("sha256_streaming ok\n");
}

void sha256_large() {
  // 64 MiB of the pattern streamed in odd chunk sizes. The pattern has period 256, so a slice at
  // absolute position p is the buffer slice starting at p % 256.
  constexpr std::size_t total = 64u << 20;
  const std::size_t sizes[] = {1, 7, 63, 64, 65, 4093, 65537, 1000003};
  const auto pattern = message((1u << 20) + 256);
  for (auto backend : kBackends) {
    Sha256 h(backend);
    std::size_t pos = 0, turn = 0;
    while (pos < total) {
      const std::size_t take = std::min(sizes[turn++ % std::size(sizes)], total - pos);
      h.update(pattern.data() + pos % 256, take);
      pos += take;
    }
    CHECK(pos == total);
    if (hex(h.finish()) != sp::crypto_vectors::kLarge64MiBDigest) {
      std::fprintf(stderr, "64 MiB digest mismatch on %s\n", name(backend));
      std::exit(1);
    }
  }
  std::printf("sha256_large ok\n");
}

void hmac_sha256_tests() {
  struct Rfc4231 { std::string key, data; const char* digest; std::size_t compare_bytes; };
  const std::vector<Rfc4231> rfc = {
      {std::string(20, '\x0b'), "Hi There", "b0344c61d8db38535ca8afceaf0bf12b881dc200c9833da726e9376c2e32cff7", 32},
      {"Jefe", "what do ya want for nothing?", "5bdcc146bf60754e6a042426089575c75a003f089d2739839dec58b964ec3843", 32},
      {std::string(20, '\xaa'), std::string(50, '\xdd'), "773ea91e36800e46854db8ebd09181a72959098b3ef8c122d9635514ced565fe", 32},
      {[] { std::string k; for (int i = 1; i <= 25; ++i) k += static_cast<char>(i); return k; }(), std::string(50, '\xcd'),
       "82558a389a443c0ea4cc819899f2083a85f0faa3e578f8077a2e3ff46729665b", 32},
      // Test case 5 is specified for the leftmost 128 bits only.
      {std::string(20, '\x0c'), "Test With Truncation", "a3b6167473100ee06e0c796c2955552b", 16},
      {std::string(131, '\xaa'), "Test Using Larger Than Block-Size Key - Hash Key First",
       "60e431591ee0b67f0d8a26aacbf5b77f8e0bc6213728c5140546040f0ee37f54", 32},
      {std::string(131, '\xaa'),
       "This is a test using a larger than block-size key and a larger than block-size data. The key needs to be hashed before being used by the HMAC algorithm.",
       "9b09ffa71b942fcb27635fbcd5b0e944bfdc63644f0713938a7f51535c3a35e2", 32},
  };
  for (auto backend : kBackends) {
    for (const auto& v : rfc) CHECK(hex_prefix(hmac_sha256(v.key, v.data, backend), v.compare_bytes) == v.digest);
    // Key lengths around the 64-byte block (shorter, equal, longer than the block) against hashlib.
    for (const auto& v : sp::crypto_vectors::kHmacVectors) {
      const auto k = key(v.key_size), m = message(v.message_size);
      if (hex(hmac_sha256(k, m, backend)) != v.digest) {
        std::fprintf(stderr, "hmac key %zu message %zu mismatch on %s\n", v.key_size, v.message_size, name(backend));
        std::exit(1);
      }
      CHECK(hmac_sha256(k.data(), k.size(), m.data(), m.size(), backend) == hmac_sha256(k, m, backend));
    }
  }
  std::printf("hmac_sha256 ok\n");
}


void constant_time_tests() {
  unsigned char a[64], b[64];
  for (int i = 0; i < 64; ++i) a[i] = b[i] = static_cast<unsigned char>(i * 3 + 1);
  CHECK(constant_time_equal(a, b, 64));
  CHECK(constant_time_equal(nullptr, nullptr, 0));
  CHECK(constant_time_equal(a, b, 0));
  for (int pos = 0; pos < 64; ++pos) {
    for (int bit = 0; bit < 8; ++bit) {
      b[pos] ^= static_cast<unsigned char>(1u << bit);
      CHECK(!constant_time_equal(a, b, 64));
      CHECK(constant_time_equal(a, b, static_cast<std::size_t>(pos)));  // equal below the flipped byte
      b[pos] ^= static_cast<unsigned char>(1u << bit);
    }
  }
  CHECK(constant_time_equal(std::string_view("abc"), std::string_view("abc")));
  CHECK(!constant_time_equal(std::string_view("abc"), std::string_view("abd")));
  CHECK(!constant_time_equal(std::string_view("abc"), std::string_view("abcd")));  // different length: unequal
  CHECK(!constant_time_equal(std::string_view("abcd"), std::string_view("abc")));
  CHECK(!constant_time_equal(std::string_view(""), std::string_view("a")));
  CHECK(constant_time_equal(std::string_view(""), std::string_view("")));
  const std::string zeros(8, '\0'), zero_then_one = std::string(7, '\0') + '\1';
  CHECK(!constant_time_equal(zeros, zero_then_one));  // embedded NULs are data, not terminators
  // Static review of constant_time_equal must also check the volatile full-length loop and the
  // absence of content-dependent early exits. Equality semantics alone cannot prove constant time;
  // do not use timing thresholds or deliberately invalid buffers to make that claim.
  // cleanse zeroes exactly the requested range.
  std::vector<unsigned char> buffer(100, 0xff);
  cleanse(buffer.data() + 10, 80);
  for (std::size_t i = 0; i < buffer.size(); ++i) CHECK(buffer[i] == (i >= 10 && i < 90 ? 0 : 0xff));
  cleanse(nullptr, 0);
  std::printf("constant_time ok\n");
}

void random_tests() {
  CHECK(random_bytes(nullptr, 0));
  for (std::size_t n : {std::size_t{0}, std::size_t{1}, std::size_t{31}, std::size_t{32}, std::size_t{33}, std::size_t{257}, std::size_t{4096}, std::size_t{70000}}) {
    std::vector<unsigned char> buffer(n + 16, 0);
    for (int i = 0; i < 8; ++i) { buffer[i] = 0xA5; buffer[8 + n + i] = 0x5A; }
    CHECK(random_bytes(buffer.data() + 8, n));
    for (int i = 0; i < 8; ++i) { CHECK(buffer[i] == 0xA5); CHECK(buffer[8 + n + i] == 0x5A); }  // never writes outside
    // Fill sanity: each byte changes from its zero sentinel in at least one independent draw.
    // Eight zero observations at a given position have probability 2^-64 for a working source;
    // this is not a statistical quality test or proof of the entropy implementation.
    std::vector<unsigned char> touched(n, 0);
    for (int draw = 0; draw < 8; ++draw) {
      CHECK(random_bytes(buffer.data() + 8, n));
      for (std::size_t j = 0; j < n; ++j) touched[j] |= buffer[8 + j];
      for (int i = 0; i < 8; ++i) { CHECK(buffer[i] == 0xA5); CHECK(buffer[8 + n + i] == 0x5A); }
    }
    for (auto byte : touched) CHECK(byte != 0);
  }
  // Independent draws differ.
  std::set<std::string> seen;
  for (int i = 0; i < 1000; ++i) {
    std::string draw(32, '\0');
    CHECK(random_bytes(draw.data(), draw.size()));
    CHECK(seen.insert(draw).second);
  }
  std::printf("random ok\n");
}

void backends_agree() {
  Rng rng{0x2545f4914f6cdd1dULL};
  std::size_t checked = 0;
  for (int round = 0; round < 4000; ++round) {
    const std::size_t n = round % 7 == 0 ? rng.below(200000) : rng.below(1500);
    std::string m(n, '\0');
    for (auto& c : m) c = static_cast<char>(rng.next());
    CHECK(sha256(m, Backend::Auto) == sha256(m, Backend::Portable));
    const std::string k = std::string(rng.below(200), '\0') + "k";
    CHECK(hmac_sha256(k, m, Backend::Auto) == hmac_sha256(k, m, Backend::Portable));
    ++checked;
  }
  std::printf("backends_agree ok (%zu random messages; Auto = %s)\n", checked, name(Backend::Auto));
}

void concurrent_use() {
  // Many threads race to the first sha256_accelerated()/Sha256 use (one-time CPU feature detection)
  // and then hash different data; each result must equal the portable reference.
  constexpr int kThreads = 8;
  std::vector<std::thread> threads;
  std::vector<int> ok(kThreads, 0);
  for (int t = 0; t < kThreads; ++t) {
    threads.emplace_back([t, &ok] {
      bool good = true;
      for (int i = 0; i < 200; ++i) {
        const auto m = message(static_cast<std::size_t>(t * 131 + i * 17));
        good = good && sha256(m, Backend::Auto) == sha256(m, Backend::Portable) &&
               hmac_sha256("key", m, Backend::Auto) == hmac_sha256("key", m, Backend::Portable);
        std::string random(16, '\0');
        good = good && random_bytes(random.data(), random.size());
      }
      ok[static_cast<std::size_t>(t)] = good;
    });
  }
  for (auto& thread : threads) thread.join();
  for (int t = 0; t < kThreads; ++t) CHECK(ok[static_cast<std::size_t>(t)]);
  std::printf("concurrent ok\n");
}
}  // namespace

int main(int argc, char** argv) {
  const std::string group = argc > 1 ? argv[1] : "";
  if (group == "sha256_vectors") sha256_vectors();
  else if (group == "sha256_streaming") sha256_streaming();
  else if (group == "sha256_large") sha256_large();
  else if (group == "hmac_sha256") hmac_sha256_tests();
  else if (group == "constant_time") constant_time_tests();
  else if (group == "random") random_tests();
  else if (group == "backends_agree") backends_agree();
  else if (group == "concurrent") concurrent_use();
  else { std::fprintf(stderr, "unknown group '%s'\n", group.c_str()); return 2; }
  return 0;
}
