// Hand-authored framing oracles from WHATWG HTML 9.2.5/9.2.6, not snapshots
// generated by the implementation. No providers, clocks, sockets or randomness.
#include "transport/sse_framer.h"

#include <array>
#include <cstdio>
#include <stdexcept>
#include <string>
#include <string_view>
#include <vector>

using namespace sp::transport;
using namespace std::string_literals;

namespace {
int failures = 0;

#define CHECK(condition)                                                        \
  do {                                                                          \
    if (!(condition)) {                                                         \
      ++failures;                                                               \
      std::fprintf(stderr, "CHECK FAILED %s:%d: %s\n", __FILE__, __LINE__,       \
                   #condition);                                                 \
    }                                                                           \
  } while (0)

struct Frame {
  std::string event;
  std::string data;
  std::string id;
  bool operator==(const Frame&) const = default;
};

// A test consumer must own its copies: SseFrame views end with the callback.
void capture(std::vector<Frame>& frames, const SseFrame& frame) {
  frames.push_back({std::string(frame.event), std::string(frame.data),
                    std::string(frame.id)});
}

void partition(std::string_view wire, const std::vector<Frame>& expected,
               SseError error, SseLimits limits,
               const std::vector<std::size_t>& cuts, std::size_t stop_after = 0) {
  SseFramer framer(limits);
  std::vector<Frame> actual;
  const SseFramer::Sink sink = [&](const SseFrame& frame) {
    capture(actual, frame);
    return stop_after == 0 || actual.size() < stop_after;
  };
  std::size_t begin = 0;
  bool accepting = true;
  for (const auto end : cuts) {
    const bool accepted = framer.feed(wire.substr(begin, end - begin), sink);
    if (!accepting) CHECK(!accepted);
    accepting = accepted;
    if (!accepted) CHECK(framer.stopped());
    begin = end;
  }
  CHECK(begin == wire.size());
  framer.finish();
  CHECK(framer.stopped());
  CHECK(framer.error() == error);
  CHECK(actual == expected);
  // Stopping is irreversible, including after a normal EOF or sink decision.
  CHECK(!framer.feed("data: forbidden\n\n", sink));
  framer.finish();
  CHECK(framer.error() == error);
  CHECK(actual == expected);
}

void all_splits(std::string_view wire, const std::vector<Frame>& expected,
                SseError error = SseError::None, SseLimits limits = {},
                std::size_t stop_after = 0) {
  // Includes empty first/last feeds and every UTF-8/BOM/CRLF/field/delimiter
  // boundary. Every expected output is independent of any run of the framer.
  for (std::size_t split = 0; split <= wire.size(); ++split) {
    partition(wire, expected, error, limits, {split, wire.size()}, stop_after);
  }
  std::vector<std::size_t> bytewise;
  for (std::size_t end = 0; end <= wire.size(); ++end) bytewise.push_back(end);
  partition(wire, expected, error, limits, bytewise, stop_after);
  // A deterministic family of multi-way partitions with different phase.
  for (std::size_t width = 2; width <= 11; ++width) {
    for (std::size_t phase = 0; phase < width; ++phase) {
      std::vector<std::size_t> cuts;
      for (auto end = phase; end < wire.size(); end += width) cuts.push_back(end);
      cuts.push_back(wire.size());
      partition(wire, expected, error, limits, cuts, stop_after);
    }
  }
}

void chunk_partition_invariant() {
  const std::string unicode = "\xc3\xa9\xe2\x82\xac\xf0\x9f\x8c\x8d";
  const std::string bom = "\xef\xbb\xbf";
  const std::string wire = bom +
      ": heartbeat\r\nid: seed\r\nevent: discarded\r\n\r\n"
      "event: custom\rdata: " + unicode +
      "\r\ndata:\ndata:  padded \r\nid: bad\0id\n\n"s +
      "data\r\r"
      "id:\ndata: next\nevent:\n\n"
      "id: final\n\n: keepalive\nretry: 1\nData: ignored\n"
      "unknown: ignored\nevent: never\n\n"
      "data: " + bom + "inside\n\n" + bom +
      "data: not-a-field\n\ndata: pending\n";
  const std::vector<Frame> expected = {
      {"custom", unicode + "\n\n padded ", "seed"},
      {"message", "", "seed"},
      {"message", "next", ""},
      {"message", bom + "inside", "final"}};
  all_splits(wire, expected);

  // All three-way splits also cover interacting saved CR and UTF-8/BOM state.
  const std::string compact = bom + "data: " + unicode + "\r\ndata\r\n\r\n";
  const std::vector<Frame> compact_expected = {{"message", unicode + "\n", ""}};
  for (std::size_t first = 0; first <= compact.size(); ++first) {
    for (std::size_t second = first; second <= compact.size(); ++second) {
      partition(compact, compact_expected, SseError::None, {},
                {first, second, compact.size()});
    }
  }
}

void fields_and_utf8_boundaries() {
  // The valid edge code points include NUL, U+007F/U+0080, U+07FF/U+0800,
  // the surrogate gap's neighbors, U+FFFF, U+10000 and U+10FFFF.
  const std::string scalars = "\0\x7f\xc2\x80\xdf\xbf\xe0\xa0\x80"
      "\xed\x9f\xbf\xee\x80\x80\xef\xbf\xbf"
      "\xf0\x90\x80\x80\xf4\x8f\xbf\xbf"s;
  all_splits("data: " + scalars + "\n\n", {{"message", scalars, ""}});
  all_splits("event: one\nevent: two\nid: a\nid: b\ndata: x:y\n\n"
             "data:\ndata\n\n"
             "event\nid\ndata:\tspaced\n\n",
             {{"two", "x:y", "b"}, {"message", "\n", "b"},
              {"message", "\tspaced", ""}});
  all_splits("\xef\xbb\xbf\xef\xbb\xbf" "data: hidden\n\n", {});
  all_splits("event: only\n\nid: only\n\n: comment\n\n", {});
  all_splits("data: a\r\ndata: b\r\r\ndata: c\n\r",
             {{"message", "a\nb", ""}, {"message", "c", ""}});
}

void pending_eof_is_not_dispatch() {
  for (const std::string_view suffix : {"data: pending", "data: pending\n",
                                      "data: pending\r", "data: pending\r\n",
                                      "data", "data:\n", "event: pending\n"}) {
    all_splits("data: delivered\n\n" + std::string(suffix),
               {{"message", "delivered", ""}});
  }
  all_splits("data:\n\n", {{"message", "", ""}});
  all_splits("data: a\r\r", {{"message", "a", ""}});
  all_splits("", {});
}

void malformed_utf8_is_partition_invariant() {
  const std::vector<std::string> malformed = {
      "\x80", "\xbf", "\xc0\xaf", "\xc1\xbf", "\xc2x", "\xc2",
      "\xe0\x80\x80", "\xed\xa0\x80", "\xe2\x82", "\xef\xbb",
      "\xf0\x80\x80\x80", "\xf4\x90\x80\x80", "\xf5\x80\x80\x80",
      "\xf8\x88\x80\x80\x80", "\xff", "\xf0\x90\x80"};
  for (const auto& invalid : malformed) {
    // Invalid even in comments or an ignored field; no accidental replacement.
    all_splits("data: before\n\n: " + invalid,
               {{"message", "before", ""}}, SseError::InvalidUtf8);
    all_splits("unknown: " + invalid + "\ndata: after\n\n", {},
               SseError::InvalidUtf8);
    all_splits(invalid, {}, SseError::InvalidUtf8);
  }
}

void sink_termination_is_not_pause() {
  const std::string wire = "data: first\n\ndata: second\n\n\xff";
  all_splits(wire, {{"message", "first", ""}}, SseError::None, {}, 1);
  // No preflight size rejection of an unconsumed suffix: stop wins at byte 9.
  all_splits("data: x\n\ndata: never\n\n", {{"message", "x", ""}},
             SseError::None, {64, 64, 9}, 1);

  SseFramer framer;
  int callbacks = 0;
  const SseFramer::Sink throwing = [&](const SseFrame&) -> bool {
    ++callbacks;
    throw std::runtime_error("consumer failure");
  };
  bool caught = false;
  try {
    framer.feed("data: x\n\ndata: y\n\n", throwing);
  } catch (const std::runtime_error&) {
    caught = true;
  }
  CHECK(caught);
  CHECK(callbacks == 1);
  CHECK(framer.stopped());
  CHECK(framer.error() == SseError::None);
  CHECK(!framer.feed("data: y\n\n", throwing));
  CHECK(callbacks == 1);
}

void independent_resource_boundaries() {
  // Line limits also protect fields that have no semantic effect.
  all_splits("data:x\r\n\r\n", {{"message", "x", ""}}, SseError::None,
             {6, 64, 64});
  all_splits("data:xx\n\n", {}, SseError::ResourceLimit, {6, 64, 64});
  all_splits(":12345\n", {}, SseError::None, {6, 64, 64});
  all_splits(":123456\n", {}, SseError::ResourceLimit, {6, 64, 64});
  all_splits("\xef\xbb\xbf" "data:x\n\n", {{"message", "x", ""}},
             SseError::None, {6, 64, 64});
  all_splits("data:\xc3\xa9\n\n", {{"message", "\xc3\xa9", ""}},
             SseError::None, {7, 64, 64});
  all_splits("data:\xc3\xa9\n\n", {}, SseError::ResourceLimit, {6, 64, 64});

  // Event budget is independent of per-line size, counts joining LF and
  // bounds the persistent id/type even when no data field has been received.
  all_splits("data:ab\ndata:cd\n\n", {{"message", "ab\ncd", ""}},
             SseError::None, {64, 5, 64});
  all_splits("data:ab\ndata:cd\n\n", {}, SseError::ResourceLimit, {64, 4, 64});
  all_splits("id:ab\nevent:c\ndata:de\n\n", {{"c", "de", "ab"}},
             SseError::None, {64, 5, 64});
  all_splits("id:ab\nevent:c\ndata:def\n\n", {}, SseError::ResourceLimit,
             {64, 5, 64});
  all_splits("id:abcdef\n", {}, SseError::ResourceLimit, {64, 5, 64});
  all_splits("event:abcdef\n", {}, SseError::ResourceLimit, {64, 5, 64});
  all_splits("id:abcde\nid:a\nevent:bbbb\nevent:b\ndata:xyz\n\n",
             {{"b", "xyz", "a"}}, SseError::None, {64, 5, 128});
  all_splits("id:abcde\n\ndata:x\n\n", {}, SseError::ResourceLimit,
             {64, 5, 64});
  all_splits("id:a\nid:ignored\0value\ndata:1234\n\n"s,
             {{"message", "1234", "a"}}, SseError::None, {64, 5, 64});
  all_splits("data:\n\n", {{"message", "", ""}}, SseError::None, {64, 0, 64});
  all_splits("data:\ndata:\n\n", {}, SseError::ResourceLimit, {64, 0, 64});
  all_splits("data:abc\n\ndata:def\n\n",
             {{"message", "abc", ""}, {"message", "def", ""}},
             SseError::None, {64, 3, 64});

  const std::string wire = "\xef\xbb\xbf: comment\r\nretry: 1\r\ndata:x\r\n\r\n";
  all_splits(wire, {{"message", "x", ""}}, SseError::None,
             {64, 64, wire.size()});
  // Last LF belongs to CRLF: the CR has already dispatched before the total
  // limit rejects LF. The error cannot erase previously delivered frames.
  all_splits(wire, {{"message", "x", ""}}, SseError::ResourceLimit,
             {64, 64, wire.size() - 1});
  all_splits("data:x\n\n", {}, SseError::ResourceLimit, {64, 64, 7});
  all_splits("\n\n", {}, SseError::None, {0, 0, 2});
  all_splits(":", {}, SseError::ResourceLimit, {0, 64, 64});
  all_splits("", {}, SseError::None, {0, 0, 0});
  all_splits("\n", {}, SseError::ResourceLimit, {64, 64, 0});
}

void misuse_is_terminal() {
  SseFramer missing;
  CHECK(!missing.feed("data:x\n\n", {}));
  CHECK(missing.error() == SseError::Misuse);
  CHECK(missing.stopped());

  for (const bool recursive_finish : {false, true}) {
    SseFramer framer;
    int callbacks = 0;
    const SseFramer::Sink sink = [&](const SseFrame& frame) {
      ++callbacks;
      CHECK(frame.data == "x");
      if (recursive_finish) {
        framer.finish();
      } else {
        CHECK(!framer.feed("data:recursive\n\n", [](const SseFrame&) {
          CHECK(false);
          return true;
        }));
      }
      // Rejected reentrancy must not invalidate this callback's borrowed view.
      CHECK(frame.data == "x");
      return true;
    };
    CHECK(!framer.feed("data:x\n\ndata:y\n\n", sink));
    CHECK(callbacks == 1);
    CHECK(framer.error() == SseError::Misuse);
    CHECK(framer.stopped());
  }
}
}  // namespace

int main() {
  struct TestCase { const char* name; void (*run)(); };
  const std::array tests = {
      TestCase{"ChunkPartitionInvariant", chunk_partition_invariant},
      TestCase{"FieldsAndUtf8Boundaries", fields_and_utf8_boundaries},
      TestCase{"PendingEofIsNotDispatch", pending_eof_is_not_dispatch},
      TestCase{"MalformedUtf8PartitionInvariant", malformed_utf8_is_partition_invariant},
      TestCase{"SinkTerminationIsNotPause", sink_termination_is_not_pause},
      TestCase{"IndependentResourceBoundaries", independent_resource_boundaries},
      TestCase{"MisuseIsTerminal", misuse_is_terminal}};
  for (const auto& test : tests) {
    const int before = failures;
    test.run();
    std::fprintf(stderr, "%s %s\n", failures == before ? "PASS" : "FAIL", test.name);
  }
  return failures == 0 ? 0 : 1;
}
