#!/usr/bin/env python3
"""Regenerate tests/crypto_vectors.h from Python's hashlib/hmac (the independent reference).

Usage: python3 tests/support/generate_crypto_vectors.py > tests/crypto_vectors.h
The message for every table is the deterministic byte pattern defined in crypto_test.cpp:
  message byte i = (i * 167 + 13) mod 256,  HMAC key byte i = (i * 29 + 5) mod 256.
"""
import hashlib
import hmac

def message(n):
    return bytes((i * 167 + 13) & 0xFF for i in range(n))

def key(n):
    return bytes((i * 29 + 5) & 0xFF for i in range(n))

KEY_SIZES = [0, 1, 31, 32, 33, 63, 64, 65, 128, 129, 300]
MESSAGE_SIZES = [0, 1, 55, 56, 63, 64, 65, 200, 1000]
LARGE = 64 << 20

print("// Generated by tests/support/generate_crypto_vectors.py with Python hashlib/hmac; do not edit.")
print("// Message byte i = (i * 167 + 13) mod 256, HMAC key byte i = (i * 29 + 5) mod 256.")
print("#pragma once")
print("#include <cstddef>")
print()
print("namespace sp::crypto_vectors {")
print("// SHA-256 of the first n pattern bytes, n = 0..300 (covers 55/56/57/63/64/65/119/120/121/127/128/129).")
print("inline constexpr const char* kLengthDigests[301] = {")
for n in range(301):
    print(f'    "{hashlib.sha256(message(n)).hexdigest()}",')
print("};")
print()
print("// SHA-256 of the first 64 MiB of the pattern.")
block = message(256)
big = hashlib.sha256()
for _ in range(LARGE // 256):
    big.update(block)
print(f'inline constexpr const char* kLarge64MiBDigest = "{big.hexdigest()}";')
print()
print("struct HmacVector { std::size_t key_size, message_size; const char* digest; };")
print("inline constexpr HmacVector kHmacVectors[] = {")
for ks in KEY_SIZES:
    for ms in MESSAGE_SIZES:
        print(f'    {{{ks}, {ms}, "{hmac.new(key(ks), message(ms), hashlib.sha256).hexdigest()}"}},')
print("};")
print("}  // namespace sp::crypto_vectors")
