#pragma once
// Generated from tools/vision_fixture.mjs geometry; no production encoder goldens.
#include "core/image.h"
#include <memory>
#include <string>
#include <string_view>
namespace vision_test {
inline constexpr std::string_view question = "Count the red circles and blue squares in the image. Report red_circles, blue_squares, and weighted = 2 * red_circles + blue_squares as three integer fields in JSON.";
inline constexpr std::string_view secret = "VISION_SYNTHETIC_KEY";
inline constexpr std::string_view private_signature = "VISION_PRIVATE_SIGNATURE";
struct Scene {
  unsigned red, blue, weighted;
  std::shared_ptr<const std::string> base64;
  sp::Image image() const { return {"image/png", base64, sp::ImageDetail::Auto}; }
  std::string answer() const {
    return "{\"red_circles\":" + std::to_string(red) + ",\"blue_squares\":" + std::to_string(blue) + ",\"weighted\":" + std::to_string(weighted) + '}';
  }
};
inline const Scene& scene_a() {
  static const Scene value{3, 2, 8,
    std::make_shared<const std::string>(
      "iVBORw0KGgoAAAANSUhEUgAAAoAAAAHgCAIAAAC6s0uzAAAKTklEQVR42u3VwRGDMBAEQYLgw5tIyD8PpYFzoKwT3HaXIxDe"
      "m+0GAMptngAABBgABBgAEGAAEGAAQIABQIABAAEGAAEGAAQYAAQYAAQYABBgABBgAECAAUCAAQABBgABBgAEGAAEGAAEGAAQ"
      "YAAQYABAgAFAgAEAAQYAAQYABBgABBgABBgAEGAAEGAAQIABQIABAAEGAAEGAAQYAAQYAAQYABBgABBgAECAAUCAAQABBgAB"
      "BgAEGAAEGAAEGAAQYAAQYABAgAFAgAEAAQYAAQYABBgABBgABBgAEGAAEGAAQIABQIABAAEGAAEGAAQYAAQYAAQYABBgABBg"
      "AECAAUCAAQABBgABBgAEGAAEGAAEGAAQYAAQYABAgJsax+kRADdHgJn1j3/283SAmyPA1G3AKj5kv0baz0d3cxDg/huwCgEW"
      "YNwcAWbxDExCgAUYN0eAWTYDkxBgAcbNEWCWzcAkBFiA3Rw3R4DN4BU/n0OABdjNcXME2BLsQYAFGDcHAc5Ygj0IsAC7OW6O"
      "AJuBSQiwAOPmIMBhS7AHARZgN8fNEWBLsAcBFmDcHAQ4aQn2IMAC7Oa4OQJsCfYgwAKMm4MAJy3BHgRYgN0cN0eAjcEYBFiA"
      "cXMQ4Jgl2IMAC7Cb4+YIsCXYgwALMG4OApy0BHsQYAF2c9wcATYGYxBgAcbNEWBilmAPAizAbo6bI8DGYAwCLMC4OQJMzBLs"
      "QYAF2M1xcwTYGIxBgAUYN0eAiVmCPQiwALs5bo4AG4MxCLAAuzlujgATswR7EGABdnPcHAE2BmMQYAF2c9wcATYGY0CABdjN"
      "cXME2BLsQYAF2M1xcwTYGIwBARZgN8fNEWBjMAYBFmA3x80RYEuwBwEWYNwcN0eAjcEYBFiA3Rw3R4CNwRgEWIBxc9wcATYG"
      "YxBgAXZz3BwBNgZjEGABdnPcHAE2BmNAgAXYzXFzBNgYjEGABdjNcXME2BiMAQEWYDfHzRFgYzAGARZgN8fNEWBLsAcBFmDc"
      "HDdHgO3BEgRYgN0cN0eAjcEYBFiAcXPcHAE2BmMQYAF2c9wcATYGYxBgAXZz3BwBNgZjQIAF2M1xcwTYGIxBgAXYzXFzBNgY"
      "jAEBFmA3x80RYGMwBgEWYDfHzRFgYzAGBBg3x80RYHuwBAEWYDfHzRFgYzAGARZg3Bw3R4CNwRgEWIDdHDdHgO3BEgRYgHFz"
      "BBhjQIAF2M1xcwTYGIxBgAXYzXFzBNgeLAEBFmA3x80RYGMwBgEWYDfHzRFge7AEBBg3x80RYGMwBgEWYDfHzRFge7AEARZg"
      "3Bw3R4CNwRgEWIDdHDdHgO3BEgRYgHFzBBhjQIAF2M1xcwTYHixBgAXYzXFzBJjbEhBgAXZz3BwBtgdLEGABdnPcHAE2BmNA"
      "gHFz3BwBtgdLEGABdnPcHAG2B0sQYAHGzUGAU/fgkwmwALs5bo4A24MlCLAA4+YgwN334DMJsAC7OW6OAJuEGQiwAOPmIMCt"
      "9+CjCLAAuzlujgDbgyUIsADj5iDArSfhEwiwALs5bo4Am4QZCLAA4+YgwH0n4akFWIBxcwSY0kl4XgEWYNwcAaZuFR5TgAUY"
      "N0eAqVuFpwPcHAFm1k48AuDmCDAAIMAAIMAAgAADgAADAAIMAAIMAAgwAAgwAAgwACDAACDAAIAAA4AAAwACDAACDAAIMAAI"
      "MAAIMAAgwAAgwACAAAOAAAMAAgwAAgwACDAACDAACDAAIMAAIMAAgAADgAADAAIMAAIMAAgwAAgwAAgwACDAACDAAIAAA4AA"
      "AwACDAACDAAIMAAIMAAIMAAgwAAgwACAAAOAAAMAAgwAAgwACDAACDAACDAAIMAAIMAAgAADgAADAAIMAAIMAAgwAAgwACDA"
      "ACDAACDAAIAAA4AAAwACDAACDAAIMAAIMAAgwAAgwAAgwACAAAOAAAMAAgwAAgwACDAACDAAIMAAIMAAIMAAgAADgAADAAIM"
      "AAIMAAgwAAgwACDAACDAACDAAIAAA4AAAwACDAACDAAIMAAIMAAgwAAgwAAgwACAAAOAAAMAAgwAAgwACDAACDAAIMAAIMAA"
      "IMAAgAADgAADAAIMAAIMAAgwAAgwACDAACDAACDAAIAAA4AAAwACDAACDAAIMAAIMMAq4zg9AgIMMKuyz36eDgHmM/ZrpP18"
      "9H7dVWIEGAEWYFZ2V4kRYARYgFmcXhlGgBFgAWZZemUYAUaABZhl6ZVhBBgBFmDpfcXP50CAEWABVl8NRoARYAEmo74ajAAj"
      "wAIsvTKMACPAAkxYfTUYAUaABVh9NRgBRoAFmKT6ajACjAALsPpqMAKMAAswSfXVYAQYARZgARZgBBgBFmBi6qvBCDACLMDq"
      "q8EIMAIswCTVV4MRYARYgAVYgBFgBFiAiamvBiPACLAAC7AAI8AIsAATU18NRoARYAEWYAFGgBFgASamvhqMACPAAizAAowA"
      "I8ACTEx9NRgBRoAFWIAFGAFGgAVYgAUYBBgBFmD11WAEGAEWYAEWYAQYBFiABViAEWAEWIDVV4MRYBBgBFiAEWAEWIAFWIAR"
      "YARYgBFgAUaAEWABFmABRoARYAEWYAEGAUaABViABRgBRoAFWIAFGAEGARZgARZgBBgBFmD11WAEGAQYDVZfBBgBFmABFmAE"
      "GAEWYARYgBFgBFiABViAEWAEWIAFWIBBgBFgARZgAUaAEWABFmABRoBBgAVYgAUYAUaABViABRgBBgFGg9UXAUaABViABRgB"
      "RoAFGAEWYAQYARZgDVZfBBgBFmAEGAQYARZgARZgBBgBFmANVl8EGARYgAVYgBFgBFiANVh9EWAQYARYgBFgBFiANVh9EWAE"
      "WIARYAFGgBFgAdZg9UWAEWABRoBBgBFgAdZg9UWAEWAB5lZfEGAEWIA1WH0RYARYgAVYgBFgEGA0WH0RYARYgDVYfRFgBFiA"
      "SW2wT4YAI8ACrMHqiwAjwAJM9wb7TAgwAizAMiy9CDACLMC0brCPggAjwAKsweqLACPAAkzrDPsECDACLMAyLL0IMAIswPTN"
      "sKdGgBFgAaY0w54XAUaABZi6EntMBBigrsSeDgEGmNVmj4AAAwACDAACDAACDAAIMAAIMAAgwAAgwACAAAOAAAMAAgwAAgwA"
      "AgwACDAACDAAIMAAIMAAgAADgAADAAIMAAIMAAIMAAgwAAgwACDAACDAAIAAA4AAAwACDAACDAACDAAIMAAIMAAgwAAgwACA"
      "AAOAAAMAAgwAAgwAAgwACDAACDAAIMAAIMAAgAADgAADAAIMAAIMAAgwAAgwAAgwACDAACDAAIAAA4AAAwACDAACDAAIMAAI"
      "MAAIMAAgwAAgwACAAAOAAAMAAgwAAgwACDAACDAACDAAIMAAIMAAgAADgAADAAIMAAIMAAgwAAgwAAgwACDAACDAAIAAA4AA"
      "AwACDAACDAAIMAAIMAAIMAAgwAAgwACAAAOAAAMAAgwAAgwACDAACDAACDAAIMAAIMAAgAADgAADAAIMAAIMAAgwAAgwAAgw"
      "ACDAACDAAMBf/QC5InloZMmLjQAAAABJRU5ErkJggg==")};
  return value;
}
inline const Scene& scene_b() {
  static const Scene value{5, 1, 11,
    std::make_shared<const std::string>(
      "iVBORw0KGgoAAAANSUhEUgAAAoAAAAHgCAIAAAC6s0uzAAALOklEQVR42u3VwQ2DUAxEQYrIhTOVpP8+aANaiJC+TbwzSgVk"
      "v992AQDlNp8AAAQYAAQYABBgABBgAECAAUCAAQABBgABBgAEGAAEGAAEGAAQYAAQYABAgAFAgAEAAQYAAQYABBgABBgABBgA"
      "EGAAEGAAQIABQIABAAEGAAEGAAQYAAQYAAQYABBgABBgAECAAUCAAQABBgABBgAEGAAEGAAEGAAQYAAQYABAgAFAgAEAAQYA"
      "AQYABBgABBgABBgAEGAAEGAAQIABQIABAAEGAAEGAAQYAAQYAAQYABBgABBgAECAAUCAAQABBgABBgAEGAAEGAAEGAAQYAAQ"
      "YABAgAFAgAEAAQYAAQYABBgABBgABBgAEGAAEGAAQICHOvfDR8ByQIBZdSuf/Xw6y7EcEGDqrqd7ajmWM97ne6b9/OkC/E/X"
      "0z21HMsRYAEWYJoPqGNqOZYjwAIswLQdUMfUcixHgAVYgGk7oI6p5ViOAAuwADugr/j5OyzHcgRYgAXYDXVJsRwEWIAFOOOG"
      "uqSWYzkCLMAC7IA6plgOAizAAhx2Q11Sy7EcARZgAXZDXVIsBwEWYAFOuqEuqeVYjgALsAC7oS6p5VgOAizAApx0Q11Sy7Ec"
      "ARZgAXZGnVHLsRwEGAGOuaEuqeVYjgALsAC7oS6p5VgOAowAJ91Ql9RyLEeABViAnVFn1HIsBwEWYGJuqEtqOZYjwAIswM6o"
      "M2o5liPAAizAxNxQl9RyLEeABViAnVFn1HIsR4AFWICJuaEuqeVYjgALsAA7o86o5ViOAAuwABNzQ11Sy7EcARZgAXZGnVHL"
      "sRwBFmABdkadUSzHcgRYgAXYDXVJLcdyBFiABdgZdUaxHMsRYAEWYGfUGbUcyxFgARZgN9QltRzLQYAFWICdUWfUcixHgAVY"
      "gJ1RZ9RyLAcBFmABdkadUcuxHAEWYAF2Rp1Ry7EcARZgAXZGnVEsx3IEWIAF2Bl1Ri3HcgRYgAXYGXVGsRzLEWABFmBn1Bm1"
      "HMsRYAEWYDfUJbUcy0GABViAXVI31HIsR4AFWICdUWfUciwHARZgAXZGnVHLsRwBFmABdkadUcuxHAEWYAF2Rp1RLMdyBFiA"
      "BdgZdUYtx3IEWIAF2Bl1RrEcyxFgARZgZ9QZtRzLEWABFmBn1Bm1HMtBgAVYgF1SN9RyLEeABViAnVFn1HIsBwEWYAF2Rp1R"
      "y7EcARZgAXZJ3VDLsRwBFmABxhnFcixHgAVYgJ1RZ9RyLEeABViAXVI3FMuxHAEWYAF2Rp1Ry7EcARZgAXZJ3VAsBwEWYAF2"
      "Rp1Ry7EcARZgAXZJ3VDLsRwEWIAF2Bl1Ri3HcgRYgAXYJXVDLcdyEGABxhnFcixHgAVYgF1SN9RyLEeABViAudxQLAcBFmAB"
      "dkndUMuxHAEWYAF2Rp1RLAcBFmABdkndUMuxHAEWYAF2Sd1QLAcBFmABTr2k/jLLsRwBFmABdkndUMuxHAQYAZ5+Sf1NlmM5"
      "AizAAuyYOqBYDgIswAI8+pL6UyzHcgRYgAXYJXVDsRwEWIAFePQx9RdYjuUIsAALsGPqgGI5CLAAC/DcY+pTW47lCLAACzCl"
      "x9TntRzLEWABFmDq7qmPaTmWI8ACLMDU3VOfznIsBwSYVRfWR8ByQIABAAEGAAEGAAQYAAQYABBgABBgAECAAUCAAUCAAQAB"
      "BgABBgAEGAAEGAAQYAAQYABAgAFAgAFAgAEAAQYAAQYABBgABBgAEGAAEGAAQIABQIABQIABAAEGAAEGAAQYAAQYABBgABBg"
      "AECAAUCAAUCAAQABBgABBgAEGAAEGAAQYAAQYABAgAFAgAFAgAEAAQYAAQYABBgABBgAEGAAEGAAQIABQIABQIABAAEGAAEG"
      "AAQYAAQYABBgABBgAECAAUCAAQABBgABBgABBgAEGAAEGAAQYAAQYABAgAFAgAEAAQYAAQYAAQYABBgABBgAEGAAEGAAQIAB"
      "QIABAAEGAAEGAAEGAAQYAAQYABBgABBgAECAAUCAAQABBgABBgABBgAEGAAEGAAQYAAQYABAgAFAgAEAAQYAAQYAAQYABBgA"
      "BBgAEGAAEGAAQIABQIABAAEGAAEGAAEGAAQYAAQYABBgABBgAECAAUCAAQABBgABBgABBgAEGAAEGAAQYAAQYABAgAFAgPnR"
      "uR8+ApaD5Qgwqxb/7OfTWY7lYDkCTN0b8Cosx3KwHAGm8w14FZZjOViOANP8DDwJy7EcLEeAaXsGnoTlWA6WI8C0PQNPwnIs"
      "x3IsR4A9g1f8/B2WYzmWYzkC7CV4D1gOloMAZ7wE78FyLMdyLEeAPQNPAsvBchDgsJfgPViO5ViO5Qiwl+A9YDlYDgKc9BK8"
      "B8uxHMuxHAH2ErwHy7EcLAcBTnoJ3oPlWI7lWI4Aewweg+VYDpaDAMe8BO/BcizHcixHgL0E78FyLAfLQYCTXoL3YDmWYzmW"
      "I8Aeg8dgOZaD5QgwMS/Be7Acy7EcyxFgj8FjsBzLwXIEmJiX4D1YjuVYjuUIsMfgMViO5WA5AkzMS/AeLMdyLMdyBNhj8Bgs"
      "x3Isx3IEmJiX4D1YjuVYjuUIsMfgMViO5ViO5Qiwx+AxYDmWYzmWI8BegvdgOZZjOZYjwB6Dx4DlWI7lWI4Aewweg+VYjuVY"
      "jgB7Cd6D5VgOlmM5AuwxeAyWYzmWYzkC7DF4DJZjOViO5Qiwx+AxWI7lWI7lCLDH4DFYjuVYjuUIsMfgMWA5lmM5liPAHoPH"
      "YDmWYzmWI8Aeg8eA5ViO5ViOAHsMHoPlWI7lWI4Aewneg+VYDpZjOQLsPXgJlmM5lmM5AuwxeAyWYzlYjuUIsMfgMViO5ViO"
      "5Qiwx+AxWI7lWI7lCLDH4DFgOZZjOZYjwB6Dx2A5lmM5liPAHoPHgOVYjuVYjgB7DB6D5ViO5ViOAHsMHoPlWA6WYzkC7D14"
      "CZZjOZZjOQLsMXgMlmM5WI7lCLDH4DFYjuVYjuUIsPfgJViO5WA5AozHgOVYjuVYjgB7DB6D5ViO5ViOAHsPXgKWYzmWYzkC"
      "7DF4DJZjOZZjOQLsPXgJWA6WYzkC7DF4DJZjOZZjOQLsPXgJlmM5WI7lCLDH4DFYjuVYjuUIsPfgJViO5WA5AozHgOVYjuVY"
      "jgB7D16C5ViO5ViOAHN5CVgOlmM5Auw9eAmWYzmWYzkC7DF4DFgOlmM5Auw9eAmWYzmWYzkC7D14CVgOloMAp74Hf5nlWI7l"
      "WI4Aew9eguVYDpaDAE9/D/4my7Ecy7EcAfYkPAMsB8tBgEe/B3+K5ViO5ViOAHsPXgKWg+UgwKOfhL/AcizHcixHgD0JzwDL"
      "wXIQ4LlPwqe2HMvBcgSY0ifh81qO5WA5Akzdq/AxLcdysBwBpu5V+HSWYzlYjgCz6p34CFgOliPAAIAAA4AAAwACDAACDAAI"
      "MAAIMAAgwAAgwAAgwACAAAOAAAMAAgwAAgwACDAACDAAIMAAIMAAIMAAgAADgAADAAIMAAIMAAgwAAgwACDAACDAACDAAIAA"
      "A4AAAwACDAACDAAIMAAIMAAgwAAgwAAgwACAAAOAAAMAAgwAAgwACDAACDAAIMAAIMAAIMAAgAADgAADAAIMAAIMAAgwAAgw"
      "ACDAACDAACDAAIAAA4AAAwACDAACDAAIMAAIMAAgwAAgwACAAAOAAAOAAAMAAgwAAgwACDAACDAAIMAAIMAAgAADgAADgAAD"
      "AAIMAAIMAAgwAAgwACDAACDAAIAAA4AAA4AAAwACDAACDAAIMAAIMAAgwAAgwACAAAOAAAOAAAMAAgwAAgwACDAACDAAIMAA"
      "IMAAgAADgAADgAADAAIMAAIMAAgwAAgwACDAAPBuN28WbW+l8hnAAAAAAElFTkSuQmCC")};
  return value;
}
} // namespace vision_test
